#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# ── Configuration ─────────────────────────────────────────────────────────
export GH_REPO="Simi24/simonepetta.com"          # gh secret/variable target
ENV_FILE="$HOME/.config/simonepetta/cloudflare.env"  # local-only, never in a repo
ZONE_NAME="simonepetta.com"
CF_API="https://api.cloudflare.com/client/v4"
TOKENS_URL="https://dash.cloudflare.com/profile/api-tokens"
mkdir -p "$(dirname "$ENV_FILE")" && chmod 700 "$(dirname "$ENV_FILE")"

# cf_code TOKEN PATH: HTTP status of a read-only GET against the Cloudflare API.
cf_code() {
  curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $1" "$CF_API$2" || true
}

# probe TOKEN "label|path|ok-codes" ...: checks each capability, prints ✓/✗,
# returns the number of failures. ok-codes is a space-separated list.
probe() {
  local token="$1"; shift
  local failures=0 spec label path ok code
  for spec in "$@"; do
    IFS='|' read -r label path ok <<<"$spec"
    code=$(cf_code "$token" "$path")
    if [[ " $ok " == *" $code "* ]]; then
      printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
    else
      printf '  %s✗%s %s %s(HTTP %s)%s\n' "$YELLOW" "$RESET" "$label" "$DIM" "$code" "$RESET"
      failures=$((failures + 1))
    fi
  done
  return "$failures"
}

banner "simonepetta.com: token Cloudflare"

# ── 1. Preflight ──────────────────────────────────────────────────────────
stage "Controlli iniziali"
for cmd in gh curl jq; do
  command -v "$cmd" >/dev/null 2>&1 || { warn "manca '$cmd': installalo e rilancia."; exit 1; }
done
gh auth status >/dev/null 2>&1 || { warn "gh non è autenticato: lancia 'gh auth login' e rilancia."; exit 1; }
say "gh, curl e jq ci sono, gh è autenticato. Secret e variabili andranno su $GH_REPO."

ZONE_ID=""; CLOUDFLARE_ACCOUNT_ID=""
if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  zone_json=$(curl -s -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" "$CF_API/zones?name=$ZONE_NAME" || true)
  ZONE_ID=$(jq -r '.result[0].id // empty' <<<"$zone_json")
  CLOUDFLARE_ACCOUNT_ID=$(jq -r '.result[0].account.id // empty' <<<"$zone_json")
fi
if [[ -n "$CLOUDFLARE_ACCOUNT_ID" && -n "$ZONE_ID" ]]; then
  say "Account e zona ricavati dal token che hai già in ~/.zshrc."
else
  say "Non riesco a ricavarli da solo: servono dalla dashboard."
  open_url "https://dash.cloudflare.com/"
  step "Apri il dominio $ZONE_NAME: nella colonna di destra della Overview trovi Zone ID e Account ID."
  ask CLOUDFLARE_ACCOUNT_ID "Account ID:"
  ask ZONE_ID "Zone ID:"
fi
note "Account ID: $CLOUDFLARE_ACCOUNT_ID"
note "Zone ID:    $ZONE_ID"
set_var CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env TF_VAR_cloudflare_account_id "$CLOUDFLARE_ACCOUNT_ID"
write_env TF_VAR_cloudflare_zone_id "$ZONE_ID"
pause "Avanti col token per la CI"

# ── 2. CI token ───────────────────────────────────────────────────────────
stage "Token per la CI (GitHub Actions)"
CI_DONE=0
if gh secret list 2>/dev/null | grep -q "^CLOUDFLARE_API_TOKEN\b"; then
  say "Il secret CLOUDFLARE_API_TOKEN è già su $GH_REPO."
  confirm "Lo tengo e salto le tappe 2 e 3?" && CI_DONE=1
fi
if (( ! CI_DONE )); then
say "Serve alle Actions per deployare i Worker. Non viene salvato sul Mac."
open_url "$TOKENS_URL"
step "Clicca 'Create Token'."
step "Accanto a 'Edit Cloudflare Workers' clicca 'Use template'."
step "Rinomina il token in: simonepetta-ci"
step "Account Resources: Include → il tuo account."
step "Zone Resources: Include → Specific zone → $ZONE_NAME"
step "'Continue to summary' → 'Create Token' → copia il token (lo vedi una volta sola)."
ask_secret CF_CI_TOKEN "Incolla il token CI (input nascosto):"
fi

# ── 3. Verify CI token ────────────────────────────────────────────────────
stage "Verifica del token CI"
while (( ! CI_DONE )); do
  say "Provo il token con chiamate di sola lettura:"
  if probe "$CF_CI_TOKEN" \
      "token attivo|/user/tokens/verify|200" \
      "legge la zona $ZONE_NAME|/zones/$ZONE_ID|200" \
      "Worker (script)|/accounts/$CLOUDFLARE_ACCOUNT_ID/workers/scripts|200" \
      "Worker (Custom Domain)|/accounts/$CLOUDFLARE_ACCOUNT_ID/workers/domains|200"; then
    set_secret CLOUDFLARE_API_TOKEN "$CF_CI_TOKEN"
    break
  fi
  warn "Il token non ha tutto. Modificalo su $TOKENS_URL (Edit), oppure creane uno nuovo."
  confirm "Vuoi incollare di nuovo il token e ritestare?" || { SKIPPED+=("GitHub secret CLOUDFLARE_API_TOKEN (token CI incompleto)"); break; }
  ask_secret CF_CI_TOKEN "Incolla il token CI (input nascosto):"
done
unset CF_CI_TOKEN 2>/dev/null || true
(( CI_DONE )) && say "Token CI già a posto: salto."
pause "Avanti col token per Terraform"

# ── 4. Terraform token ────────────────────────────────────────────────────
stage "Token per Terraform (solo su questo Mac)"
say "Terraform gestisce AI Gateway, Turnstile, DNS e il redirect di www."
open_url "$TOKENS_URL"
step "Clicca 'Create Token' → 'Use template' su 'Edit Cloudflare Workers'."
step "Rinomina il token in: simonepetta-terraform"
step "Con '+ Add more' aggiungi queste righe di permessi:"
note "    Account | AI Gateway   | Edit"
note "    Account | Turnstile    | Edit"
note "    Account | Workers AI   | Read"
note "    Zone    | DNS          | Edit"
note "    Zone    | Single Redirect | Edit  (a volte si chiama 'Dynamic URL Redirects')"
step "Account Resources: il tuo account. Zone Resources: Specific zone → $ZONE_NAME"
step "'Continue to summary' → 'Create Token' → copia il token."
ask_secret TF_VAR_cloudflare_api_token "Incolla il token Terraform (input nascosto):"

# ── 5. Verify Terraform token ─────────────────────────────────────────────
stage "Verifica del token Terraform"
while :; do
  say "Provo ogni permesso con chiamate di sola lettura:"
  if probe "$TF_VAR_cloudflare_api_token" \
      "token attivo|/user/tokens/verify|200" \
      "DNS della zona|/zones/$ZONE_ID/dns_records|200" \
      "Single Redirect|/zones/$ZONE_ID/rulesets/phases/http_request_dynamic_redirect/entrypoint|200 404" \
      "AI Gateway|/accounts/$CLOUDFLARE_ACCOUNT_ID/ai-gateway/gateways|200" \
      "Turnstile|/accounts/$CLOUDFLARE_ACCOUNT_ID/challenges/widgets|200" \
      "Workers AI|/accounts/$CLOUDFLARE_ACCOUNT_ID/ai/models/search|200" \
      "Worker (script)|/accounts/$CLOUDFLARE_ACCOUNT_ID/workers/scripts|200"; then
    write_env TF_VAR_cloudflare_api_token "$TF_VAR_cloudflare_api_token"
    chmod 600 "$ENV_FILE"
    break
  fi
  warn "Mancano dei permessi: aggiungili al token (Edit) su $TOKENS_URL e ritesta."
  note "(404 su Single Redirect va bene: vuol dire solo che non ci sono ancora regole.)"
  confirm "Hai sistemato il token? Ritesto (incolli di nuovo solo se ne hai creato uno nuovo)" || { SKIPPED+=("token Terraform incompleto: non salvato"); break; }
  ask_secret NEW_TF_TOKEN "Incolla il token Terraform, o Invio se hai solo modificato quello di prima:"
  [[ -n "$NEW_TF_TOKEN" ]] && TF_VAR_cloudflare_api_token="$NEW_TF_TOKEN"
done
note "Terraform lo leggerà da $ENV_FILE (set -a; source ...; set +a). ~/.zshrc non è stato toccato."

finish
